### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by Vuurvos1** [ralfz123/frontend-data#1]
## Repository

- [x] Is the repo called exactly 'frontend-data'?
- [x] link to live demo on GitHub pages
- [x] description
  - Nice and clear in the readme
- [x] concept
- [x] gitignore
  - Missing would recommend the [Node .gitignore by Github](https://github.com/github/gitignore/blob/master/Node.gitignore) for starters 
- [x] image
  - Missing screenshot of the live version
- [x] link to example used to build visualization (screenshots) concept described in readme? Research question, data to be used, sketch of datavisualization.
  - Missing
- [x] data used described properly? (what's done with invalid and empty values?)
  - Data structure is described, not what is done with empyt values
- [x] plagiarism and acknowledgements
  - Maybe missing a few sources

## Wiki

- [x] can you follow the datacleaning and transforming process?
  - Couldn't find in Functional programming or Frontend data wiki
- [x] Is there an example of a data object before and after this process?
  - Not in the wiki, in the Readme there is a final dataset structure
- [x] Is the update pattern (data flow) documented
  - Might want to add an example of your own code or comment the code in the wiki
- [x] Are there pages documenting what the student learned
  - Mainly in the logbook

## Live demo

- [x] Does the visualization makes sense on it's own? (labels, axis, titles)
  - The interface for the visualization is clear except it is missing data (maybe that is only an issue for me?)
- [x] Does the data shown change through interaction?
  - Not yet

## Other notes
- You might want to move some stuff over from your functional programming to the frontend data repo 
- Some small things that still need to be fixed but overall going great, keep it up!

**Comment by ralfz123** [comment]
Thanks voor de feedback @Vuurvos1 !

Ik heb wel nog een aantal dingen:
1. Ik heb geen voorbeeld gebruikt, dit is helemaal uit eigen concept bedacht. _Research question, data to be used, sketch of datavisualization_ is wel genoteerd in readme

2. datacleaning and tranforming --> _"Couldn't find in Functional programming or Frontend data wiki"_ --> [hier](https://github.com/ralfz123/functional-programming/wiki/Functional-Patterns) staat het ;)

Nogmaals thanks!

🔥 🔥 🔥
